routes:

    _container_debug:
        url: /_debug/container
        controller: controller._container_debug
        action: containerDebug
        methods:
          - GET

    _listeners_debug:
        url: /_debug/listeners
        controller: controller._listeners_debug
        action: listenersDebug
        methods:
          - GET

services:

    php_template_engine:
        class: \Veto\Templating\Engine\PhpEngine

    dispatcher:
        class: \Veto\Event\Dispatcher

    controller:
        _exception_handler:
            class: \Veto\Debug\Controller\ExceptionController
            one_shot: true
        _container_debug:
            class: \Veto\Debug\Controller\ContainerDebugController
            one_shot: true
        _listeners_debug:
            class: \Veto\Debug\Controller\ListenersDebugController
            one_shot: true