parameters:

    version: 0.3.0

services:

    php_template_engine:
        class: \Veto\Templating\Engine\PhpEngine

    dispatcher:
        class: \Veto\Event\Dispatcher

    controller:
        _exception_handler:
            class: \Veto\MVC\Controller\ExceptionController
            one_shot: true